# Generated by Django 6.0.4 on 2026-04-22 12:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in valid format', regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(blank=True, db_index=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('is_agent', models.BooleanField(db_index=True, default=False, help_text='Indicates if this user can list properties')),
                ('average_rating', models.FloatField(default=0.0, help_text='Denormalized average rating from reviews')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
                'indexes': [models.Index(fields=['is_agent'], name='profiles_is_agen_efc40f_idx'), models.Index(fields=['city', 'is_agent'], name='profiles_city_244921_idx'), models.Index(fields=['state', 'is_agent'], name='profiles_state_f9884f_idx')],
            },
        ),
    ]
