# Generated by Django 6.0.4 on 2026-04-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.CharField(blank=True, help_text='Service area/neighborhoods', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='license_no',
            field=models.CharField(blank=True, help_text='Real estate license number', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='property_types',
            field=models.CharField(blank=True, help_text='Types of properties handled (e.g., Residential, Commercial)', max_length=255),
        ),
    ]
