# Generated by Django 6.0.4 on 2026-04-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_area_profile_experience_profile_license_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profiles/'),
        ),
    ]
