# Generated by Django 6.0.4 on 2026-04-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.EmailField(help_text='Subscriber email address', max_length=255, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional subscriber name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether subscription is active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='When user subscribed')),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='When user unsubscribed (if applicable)', null=True)),
                ('source', models.CharField(blank=True, help_text="Where subscription came from (e.g., 'blog_page', 'footer', 'popup')", max_length=50)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'db_table': 'newsletter_subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
