# Generated by Django 6.0.4 on 2026-04-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
