# Generated by Django 6.0.4 on 2026-04-22 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in currency (currency-agnostic)', max_digits=15)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('agricultural', 'Agricultural')], max_length=50)),
                ('status', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('sold', 'Sold'), ('rented', 'Rented')], default='sale', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value pairs for flexible data (bedrooms, bathrooms, sqft, etc.)')),
                ('agent', models.ForeignKey(limit_choices_to={'is_agent': True}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=100)),
                ('feature_value', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Feature',
                'verbose_name_plural': 'Property Features',
                'db_table': 'property_features',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image_url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'db_table': 'property_images',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['agent_id'], name='properties_agent_i_c4e85a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['slug'], name='properties_slug_e22d01_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties_propert_f38ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties_status_e6008a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='properties_city_c34f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties_price_aa33af_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='properties_created_abda95_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['agent_id', 'status'], name='properties_agent_i_09424d_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyfeature',
            index=models.Index(fields=['property_id'], name='property_fe_propert_02e7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyfeature',
            index=models.Index(fields=['feature_key'], name='property_fe_feature_5181e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyfeature',
            unique_together={('property', 'feature_key')},
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property_id'], name='property_im_propert_918ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property_id', 'is_primary'], name='property_im_propert_0ad054_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('property', 'is_primary'), name='unique_primary_image_per_property'),
        ),
    ]
