# Generated by Django 6.0.4 on 2026-04-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='propertyimage',
            name='unique_primary_image_per_property',
        ),
        migrations.RemoveIndex(
            model_name='propertyimage',
            name='property_im_propert_918ab6_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyimage',
            name='property_im_propert_0ad054_idx',
        ),
        migrations.RenameField(
            model_name='propertyimage',
            old_name='property',
            new_name='property_ref',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property_ref_id'], name='property_im_propert_ccb662_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property_ref_id', 'is_primary'], name='property_im_propert_4447bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('property_ref', 'is_primary'), name='unique_primary_image_per_property'),
        ),
    ]
