# Generated by Django 6.0.4 on 2026-04-22 15:58

import apps.properties.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('properties', '0002_remove_propertyimage_unique_primary_image_per_property_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='properties_agent_i_09424d_idx',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.properties.models.property_image_upload_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='property',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('agricultural', 'Agricultural')], default='residential', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('sold', 'Sold'), ('rented', 'Rented'), ('pending', 'Pending')], default='sale', max_length=50),
        ),
    ]
