# Generated by Django 6.0.4 on 2026-04-22 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('preferred_date', models.DateField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('is_reviewed', models.BooleanField(default=False, help_text='Agent has reviewed this request')),
                ('agent', models.ForeignKey(limit_choices_to={'is_agent': True}, on_delete=django.db.models.deletion.CASCADE, related_name='received_visit_requests', to='profiles.profile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visit Request',
                'verbose_name_plural': 'Visit Requests',
                'db_table': 'visit_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_id'], name='visit_reque_agent_i_e42ca3_idx'), models.Index(fields=['user_id'], name='visit_reque_user_id_2082cb_idx'), models.Index(fields=['property_id'], name='visit_reque_propert_2c817b_idx'), models.Index(fields=['status'], name='visit_reque_status_f79881_idx'), models.Index(fields=['agent_id', 'status'], name='visit_reque_agent_i_15d822_idx'), models.Index(fields=['created_at'], name='visit_reque_created_3ab103_idx')],
            },
        ),
    ]
